//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComisionesSaludOcupacional.Models.ET01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivo
    {
        public int idArchivo { get; set; }
        public string nombre { get; set; }
        public string filePath { get; set; }
        public int idNoticia { get; set; }
        public string tipo { get; set; }
    
        public virtual Noticia Noticia { get; set; }
    }
}
