//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComisionesSaludOcupacional.Models.ET01
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentroDeTrabajo
    {
        public int idCentroDeTrabajo { get; set; }
        public string nombreCentroDeTrabajo { get; set; }
        public int idRegion { get; set; }
    }
}
