//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComisionesSaludOcupacional.Models.ET01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public int idCuenta { get; set; }
        public string nombre { get; set; }
        public string contrasena { get; set; }
        public int rol { get; set; }
        public Nullable<int> idComision { get; set; }
    
        public virtual Comision Comision { get; set; }
    }
}
