//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComisionesSaludOcupacional.Models.ET01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Representante
    {
        public int idRepresentante { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public int tipo { get; set; }
        public int estado { get; set; }
        public Nullable<int> idComision { get; set; }
    
        public virtual Comision Comision { get; set; }
    }
}
