//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComisionesSaludOcupacional.Models.ET01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Representante
    {
        public int idRepresentante { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public int tipo { get; set; }
        public System.DateTime ingreso { get; set; }
        public System.DateTime vencimiento { get; set; }
        public int estado { get; set; }
        public Nullable<int> idComision { get; set; }
    
        public virtual Comision Comision { get; set; }
    }
}
